services:
  mongo:
    image: mongo:6
    container_name: mongo_iudigital
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  monolito-api:
    image: davidmaryluz6/monolito-api:1.0
    container_name: monolito_api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/iudigital
    depends_on:
      - mongo

  ms-proyectos:
    image: davidmaryluz6/ms-proyectos:1.0
    container_name: ms_proyectos
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/iudigital
    depends_on:
      - mongo

volumes:
  mongo_data: